const router = require("express").Router({ mergeParams: true });
const multer = require("multer");
const auth = require("../midelwers/auth");
const check = require("../midelwers/Users/CheckUserToken");
const controller = require("../controllers/panels");
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 25 * 1024 * 1024 } });
router.use(auth, check);
router.get("/", controller.listPanels);
router.post("/", controller.createPanel);
router.post("/:panelId/submit-edits", controller.submitEdits);
router.post("/:panelId/cancel-edits", controller.cancelEdits);
router.get("/:panelId", controller.getPanel);
router.put("/:panelId", controller.updatePanel);
router.delete("/:panelId", controller.deletePanel);
router.post("/:panelId/claim", controller.claimPanel);
router.post("/:panelId/complete-quote", controller.completeQuote);
router.post("/:panelId/open-editing", controller.openEditing);
router.post("/:panelId/execution-pdf/request", controller.requestExecutionPdf);
router.put("/:panelId/execution-pdf/design", controller.saveExecutionPdfDesign);
router.post("/:panelId/execution-pdf/files", upload.single("file"), controller.uploadExecutionPdf);
router.get("/:panelId/execution-pdf/files/:fileId", controller.downloadExecutionPdf);
router.delete("/:panelId/execution-pdf/files/:fileId", controller.deleteExecutionPdf);
router.post("/:panelId/execution-pdf/finish", controller.finishExecutionPdf);
router.post("/:panelId/execution-pdf/skip", controller.skipExecutionPdf);
router.post("/:panelId/execution-pdf/request-changes", controller.requestExecutionPdfChanges);
router.post("/:panelId/execution/confirm", controller.confirmExecution);
router.post("/:panelId/delivery-schedule/request", controller.requestDeliverySchedule);
router.post("/:panelId/delivery-schedule/respond", controller.respondDeliverySchedule);
router.post("/:panelId/manufacturing/files", upload.single("file"), controller.uploadManufacturing);
router.get("/:panelId/manufacturing/files/:fileId", controller.downloadManufacturing);
router.get("/:panelId/manufacturing/archive", controller.downloadManufacturingArchive);
router.delete("/:panelId/manufacturing/files/:fileId", controller.deleteManufacturing);
router.post("/:panelId/manufacturing/finish", controller.finishManufacturing);
router.post("/:panelId/manufacturing/stage", controller.updateStage);
module.exports = router;
